services:
  # Backend service
  - type: web
    name: ai-writing-assistant-backend
    env: node
    buildCommand: chmod +x ./deploy-render.sh && ./deploy-render.sh
    startCommand: cd backend && node startup.js
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: DEFAULT_MODEL
        value: nvidia/llama-3.1-nemotron-nano-8b-v1:free
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_TOKENS
        value: 1000
    healthCheckPath: / 