services:
  - type: web
    name: ai-writing-assistant
    env: node
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: cd backend && node run.js
    plan: free
    healthCheckPath: /api/health
    healthCheckTimeout: 100
    disk:
      name: ai-writing-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: DEFAULT_MODEL
        value: nvidia/llama-3.1-nemotron-nano-8b-v1:free
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_TOKENS
        value: 1000
      - key: FRONTEND_URL
        fromService:
          name: ai-writing-assistant
          type: web
          property: host
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: NODE_VERSION
        value: 18.17.1
    autoDeploy: true 